---
version: "3.7"

services:

  samba:
    container_name: samba
    image: dperson/samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    stdin_open: true
    tty: true
    volumes:
      - ./sample/share:/mnt:z
      - samba_etc:/etc
      - samba_cache:/var/cache/samba
      - samba_lib:/var/lib/samba
      - samba_log:/var/log/samba
      - samba_run:/run/samba
      - type: tmpfs
        target: /tmp
    # tmpfs:
    #   - /tmp:mode=1777

    command: '-s "Mount;/mnt"'

    restart: always

volumes:
  samba_etc: {}
  samba_cache: {}
  samba_lib: {}
  samba_log: {}
  samba_run: {}

