---
version: "3.7"
services:

  openfire:
    container_name: openfire
    build: pnfr/.
    ports:
      - "9090:9090"
      - "5222:5222"
      - "7777:7777"
      - "7070:7070"
    volumes:
      - openfire_data:/var/lib/openfire
      - openfire_logs:/var/log/openfire
    restart: always

  conversejs:
    container_name: conversejs
    build: conversejs/.
    ports:
      - "381:81"
    depends_on:
      - "openfire"
    restart: always

volumes:
  openfire_data: {}
  openfire_logs: {}

